config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  namespace :users do
    get 'dashboards/index'
    resources :articles
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, length: { maximum: 10 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @articles = current_user.articles
  end
  
  def show
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to users_article_url @article
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      redirect_to users_article_url @article
    else
      render :edit
    end
  end
  
  def destroy
    @article.destroy
    redirect_to users_articles_url
  end
  
  private
  
    def article_params
      params.require(:article).permit(:title, :content, :image)
    end
    
    def set_article
      @article = current_user.articles.find_by(id: params[:id])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
    users_dashboards_index_path
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def after_update_path_for(resource)
    users_dashboards_index_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    users_dashboards_index_path
  end
  
  def after_sign_out_path_for(resource)
    user_session_path
  end
  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper
end

app/helpers/users/dashboards_helper.rb
module Users::DashboardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JitPreparation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/articles/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2 class="text-center">記事の編集</h2>
      <%= form_with(model: @article, url: users_article_path(@article), local: true) do |f| %>
              
        <div class="field">
          <%= f.label :title %><br/>
          <%= f.text_field :title, class: "form-control" %>
        </div>
              
        <div class="field">
          <%= f.label :content %><br/>
          <%= f.text_area :content, class: "form-control" %>
        </div>
              
        <div class="field">
          <%= f.label :image %><br/>
          <%= f.file_field :image, class: "form-control" %>
        </div><br/>     
              
        <div class="actions d-grid gap-2">
          <%= f.submit '更新する', class: 'btn btn-primary' %>
        </div>
      <% end %><br/>
            
      <%= link_to "戻る", users_articles_path %>
    </div>
  </div>
</div>

app/views/users/articles/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 text-center">
      <h2>記事一覧</h2>
      <div class="col-5 mx-auto d-grid gap-2">
        <%= link_to "記事新規作成", new_users_article_path, class: 'btn btn-primary' %>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>詳細表示</th>
            <th>タイトル</th>
            <th>内容</th>
            <th>画像</th>
            <th>編集・削除</th>
          </tr>
        </thead>
        <tbody class="table-group-divider align-middle">
          <% @articles.each do |article| %>
            <tr>
              <td><%= link_to "詳細", users_article_path(article), class: 'btn btn-primary' %></td>
              <td><%= article.title %></td>
              <td><%= article.content %></td>
              <td>
                <% if article.image? %>
                  <%= image_tag article.image.url, class: 'rounded-0', size: '100x100' %>
                <% end %>
              </td>
              <td>
                <%= link_to "編集", edit_users_article_path(article), class: 'btn btn-success' %>
                <%= link_to "削除", users_article_path(article), method: :delete,
                data: { confirm: "「#{article.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "戻る", users_dashboards_index_path, class: 'float-start' %>
    </div>
  </div>
</div>

app/views/users/articles/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2 class="text-center">記事の新規作成</h2>
      <%= form_with(model: @article, url: users_articles_path, local: true) do |f| %>
              
        <div class="field">
          <%= f.label :title %><br/>
          <%= f.text_field :title, class: "form-control" %>
        </div>
              
        <div class="field">
          <%= f.label :content %><br/>
          <%= f.text_area :content, class: "form-control" %>
        </div>
              
        <div class="field">
          <%= f.label :image %><br/>
          <%= f.file_field :image, class: "form-control" %>
        </div><br/>     
              
        <div class="actions d-grid gap-2">
          <%= f.submit '新規作成', class: 'btn btn-primary' %>
        </div>
      <% end %><br/>
            
      <%= link_to "戻る", users_articles_path %>
    </div>
  </div>
</div>

app/views/users/articles/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 text-center">
      <h2>記事詳細</h2>
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>内容</th>
            <th>画像</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <tr>
            <td><%= @article.title %></td>
            <td><%= @article.content %></td>
            <td>
              <% if @article.image? %>
                <%= image_tag @article.image.url, class: 'rounded-0', size: '100x100' %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
        <%= link_to "編集", edit_users_article_path(@article), class: 'btn btn-success' %>
        <%= link_to "削除", users_article_path(@article), method: :delete,
        data: { confirm: "「#{@article.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
      </div><br/>
      <div class="col-2 mx-auto d-grid gap-2">
        <%= link_to "記事一覧へ戻る", users_articles_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboards/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-3 text-center">
      <h2>Dash Boards</h2>
      <h3><%= current_user.name %></h3>
      <div class="d-grid gap-2 col-8 mx-auto">
        <%= link_to "記事一覧", users_articles_path, class: 'btn btn-lg btn-primary' %>
        <%= link_to t('.edit'), edit_user_registration_path, class: 'btn btn-lg btn-primary' %>
        <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'btn btn-lg btn-warning' %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('.sign_in'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('.sign_up'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('.forgot_your_password'), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>